### ISSUE TITLE
Relation to Hatena Diary themes?

### ISSUE THREAD

**Issue by sudofox** [tdiary/tdiary-theme#9]
Hi, I was wondering what relation tDiary themes have to those that were available for use on Hatena Diary and Hatena Group (both of which are now closed.) I notice some of these share filenames and make references to Hatena as well. I am doing archival research.

- Which came first? Hatena Diary/tDiary?
- Were any of these themes made specifically for, or for use on, Hatena -- or were they ported to be used on Hatena Diary?
- Any interesting things for someone enthusiastic about Hatena to learn?

Thanks for answering the questions.

**Comment by tdtds** [comment]
Hatena Diary was designed to have a compatible HTML structure with tDiary, and there is a certain compatibility between the two themes. tDiary's theme was released under the GPL, so Hatena contributed the theme they created to tDiary.

**Comment by sudofox** [comment]
Thank you for the information! Now I understand things better.
